name: CI
on:
  push:
    branches: [ "main" ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name:Linux
    runs-on: ubuntu-latest
    steps:
      - name: 获取代码
      - uses: actions/checkout@v3
      - name: Flutter依赖安装
      - uses: subosito/flutter-action@v2
        with:
           channel: 'stable'
      - name: 更新Linux依赖
      - run: |
         sudo apt-get update -y
         sudo apt-get install -y ninja-build libgtk-3-dev
      - run: flutter config --enable-linux-desktop
      - run: flutter build linux
      - run: flutter build web


